package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-07-25T13:35:44.689+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "FreqWarningWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface FreqWarningWebServiceSoap {

    @WebMethod(operationName = "Update_Stat", action = "http://tempuri.org/Update_Stat")
    @RequestWrapper(localName = "Update_Stat", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateStat")
    @ResponseWrapper(localName = "Update_StatResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateStatResponse")
    @WebResult(name = "Update_StatResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.FreqWarningOperationResponse updateStat(
        @WebParam(name = "dto", targetNamespace = "http://tempuri.org/")
        org.tempuri.FreqWarningStatDTO dto
    );

    @WebMethod(operationName = "Query_Stat", action = "http://tempuri.org/Query_Stat")
    @RequestWrapper(localName = "Query_Stat", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryStat")
    @ResponseWrapper(localName = "Query_StatResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryStatResponse")
    @WebResult(name = "Query_StatResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.FreqWarningStatQueryResponse queryStat(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.tempuri.FreqWarningStatQueryRequest request
    );

    @WebMethod(operationName = "Query", action = "http://tempuri.org/Query")
    @RequestWrapper(localName = "Query", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Query")
    @ResponseWrapper(localName = "QueryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryResponse")
    @WebResult(name = "QueryResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.FreqWarningQueryResponse query(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.tempuri.FreqWarningQueryRequest request
    );

    @WebMethod(operationName = "Remove_Stat", action = "http://tempuri.org/Remove_Stat")
    @RequestWrapper(localName = "Remove_Stat", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveStat")
    @ResponseWrapper(localName = "Remove_StatResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveStatResponse")
    @WebResult(name = "Remove_StatResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.FreqWarningOperationResponse removeStat(
        @WebParam(name = "statIds", targetNamespace = "http://tempuri.org/")
        org.tempuri.ArrayOfString statIds
    );

    @WebMethod(operationName = "Remove", action = "http://tempuri.org/Remove")
    @RequestWrapper(localName = "Remove", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Remove")
    @ResponseWrapper(localName = "RemoveResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveResponse")
    @WebResult(name = "RemoveResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.FreqWarningOperationResponse remove(
        @WebParam(name = "freqIds", targetNamespace = "http://tempuri.org/")
        org.tempuri.ArrayOfString freqIds
    );

    @WebMethod(operationName = "UpdateKeyword", action = "http://tempuri.org/UpdateKeyword")
    @RequestWrapper(localName = "UpdateKeyword", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateKeyword")
    @ResponseWrapper(localName = "UpdateKeywordResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateKeywordResponse")
    @WebResult(name = "UpdateKeywordResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.FreqWarningOperationResponse updateKeyword(
        @WebParam(name = "freqId", targetNamespace = "http://tempuri.org/")
        java.lang.String freqId,
        @WebParam(name = "keyword", targetNamespace = "http://tempuri.org/")
        java.lang.String keyword
    );

    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorldResponse")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String helloWorld();

    @WebMethod(operationName = "Insert_Stat", action = "http://tempuri.org/Insert_Stat")
    @RequestWrapper(localName = "Insert_Stat", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertStat")
    @ResponseWrapper(localName = "Insert_StatResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertStatResponse")
    @WebResult(name = "Insert_StatResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.FreqWarningOperationResponse insertStat(
        @WebParam(name = "dto", targetNamespace = "http://tempuri.org/")
        org.tempuri.FreqWarningStatDTO dto
    );

    @WebMethod(operationName = "Insert", action = "http://tempuri.org/Insert")
    @RequestWrapper(localName = "Insert", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Insert")
    @ResponseWrapper(localName = "InsertResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertResponse")
    @WebResult(name = "InsertResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.FreqWarningOperationResponse insert(
        @WebParam(name = "dto", targetNamespace = "http://tempuri.org/")
        org.tempuri.FreqWarningDTO dto
    );

    @WebMethod(operationName = "Update", action = "http://tempuri.org/Update")
    @RequestWrapper(localName = "Update", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Update")
    @ResponseWrapper(localName = "UpdateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateResponse")
    @WebResult(name = "UpdateResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.FreqWarningOperationResponse update(
        @WebParam(name = "dto", targetNamespace = "http://tempuri.org/")
        org.tempuri.FreqWarningDTO dto
    );
}
