
package org.tempuri;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-07-14T13:59:22.435+08:00
 * Generated source version: 3.1.11
 * 
 */
 
public class FreqHistoryWebServiceSoap_FreqHistoryWebServiceSoap_Server{

    protected FreqHistoryWebServiceSoap_FreqHistoryWebServiceSoap_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new FreqHistoryWebServiceSoapImpl();
        String address = "http://192.168.21.2:8000/FreqHistoryWebService.asmx";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new FreqHistoryWebServiceSoap_FreqHistoryWebServiceSoap_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
