package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-07-14T13:59:22.420+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "FreqHistoryWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface FreqHistoryWebServiceSoap {

    @WebMethod(operationName = "InsertFreq", action = "http://tempuri.org/InsertFreq")
    @RequestWrapper(localName = "InsertFreq", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertFreq")
    @ResponseWrapper(localName = "InsertFreqResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertFreqResponse")
    @WebResult(name = "InsertFreqResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.FreqHistoryOperationResponse insertFreq(
        @WebParam(name = "dto", targetNamespace = "http://tempuri.org/")
        org.tempuri.FreqHistoryDTO dto
    );

    @WebMethod(operationName = "InsertFreqs", action = "http://tempuri.org/InsertFreqs")
    @RequestWrapper(localName = "InsertFreqs", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertFreqs")
    @ResponseWrapper(localName = "InsertFreqsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertFreqsResponse")
    @WebResult(name = "InsertFreqsResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.FreqHistoryOperationResponse insertFreqs(
        @WebParam(name = "dtos", targetNamespace = "http://tempuri.org/")
        org.tempuri.ArrayOfFreqHistoryDTO dtos
    );

    @WebMethod(operationName = "UpdateByFreqId", action = "http://tempuri.org/UpdateByFreqId")
    @RequestWrapper(localName = "UpdateByFreqId", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateByFreqId")
    @ResponseWrapper(localName = "UpdateByFreqIdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateByFreqIdResponse")
    @WebResult(name = "UpdateByFreqIdResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.FreqHistoryOperationResponse updateByFreqId(
        @WebParam(name = "dto", targetNamespace = "http://tempuri.org/")
        org.tempuri.FreqHistoryDTO dto
    );

    @WebMethod(operationName = "RemoveByFreqId", action = "http://tempuri.org/RemoveByFreqId")
    @RequestWrapper(localName = "RemoveByFreqId", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveByFreqId")
    @ResponseWrapper(localName = "RemoveByFreqIdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveByFreqIdResponse")
    @WebResult(name = "RemoveByFreqIdResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.FreqHistoryOperationResponse removeByFreqId(
        @WebParam(name = "freqId", targetNamespace = "http://tempuri.org/")
        java.lang.String freqId
    );

    @WebMethod(operationName = "RemoveByFreqIds", action = "http://tempuri.org/RemoveByFreqIds")
    @RequestWrapper(localName = "RemoveByFreqIds", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveByFreqIds")
    @ResponseWrapper(localName = "RemoveByFreqIdsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveByFreqIdsResponse")
    @WebResult(name = "RemoveByFreqIdsResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.FreqHistoryOperationResponse removeByFreqIds(
        @WebParam(name = "freqIds", targetNamespace = "http://tempuri.org/")
        org.tempuri.ArrayOfString freqIds
    );

    @WebMethod(operationName = "Query", action = "http://tempuri.org/Query")
    @RequestWrapper(localName = "Query", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Query")
    @ResponseWrapper(localName = "QueryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryResponse")
    @WebResult(name = "QueryResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.FreqHistoryQueryResponse query(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.tempuri.FreqHistoryQueryRequest request
    );

    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorldResponse")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String helloWorld();

    @WebMethod(operationName = "UpdateByFreqIds", action = "http://tempuri.org/UpdateByFreqIds")
    @RequestWrapper(localName = "UpdateByFreqIds", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateByFreqIds")
    @ResponseWrapper(localName = "UpdateByFreqIdsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateByFreqIdsResponse")
    @WebResult(name = "UpdateByFreqIdsResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.FreqHistoryOperationResponse updateByFreqIds(
        @WebParam(name = "dtos", targetNamespace = "http://tempuri.org/")
        org.tempuri.ArrayOfFreqHistoryDTO dtos
    );
}
