
package org.tempuri;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-08-19T13:16:59.918+08:00
 * Generated source version: 3.1.11
 * 
 */
public final class FreqWarningWebServiceSoap_FreqWarningWebServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "FreqWarningWebService");

    private FreqWarningWebServiceSoap_FreqWarningWebServiceSoap_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = FreqWarningWebService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        FreqWarningWebService ss = new FreqWarningWebService(wsdlURL, SERVICE_NAME);
        FreqWarningWebServiceSoap port = ss.getFreqWarningWebServiceSoap();  
        
        {
        System.out.println("Invoking updateStatus...");
        String _updateStatus_freqId = "";
        int _updateStatus_status = 0;
        FreqWarningOperationResponse _updateStatus__return = port.updateStatus(_updateStatus_freqId, _updateStatus_status);
        System.out.println("updateStatus.result=" + _updateStatus__return);


        }
        {
        System.out.println("Invoking updateStat...");
        FreqWarningStatDTO _updateStat_dto = null;
        FreqWarningOperationResponse _updateStat__return = port.updateStat(_updateStat_dto);
        System.out.println("updateStat.result=" + _updateStat__return);


        }
        {
        System.out.println("Invoking queryStat...");
        FreqWarningStatQueryRequest _queryStat_request = null;
        FreqWarningStatQueryResponse _queryStat__return = port.queryStat(_queryStat_request);
        System.out.println("queryStat.result=" + _queryStat__return);


        }
        {
        System.out.println("Invoking query...");
        FreqWarningQueryRequest _query_request = null;
        FreqWarningQueryResponse _query__return = port.query(_query_request);
        System.out.println("query.result=" + _query__return);


        }
        {
        System.out.println("Invoking removeStat...");
        ArrayOfString _removeStat_statIds = null;
        FreqWarningOperationResponse _removeStat__return = port.removeStat(_removeStat_statIds);
        System.out.println("removeStat.result=" + _removeStat__return);


        }
        {
        System.out.println("Invoking remove...");
        ArrayOfString _remove_freqIds = null;
        FreqWarningOperationResponse _remove__return = port.remove(_remove_freqIds);
        System.out.println("remove.result=" + _remove__return);


        }
        {
        System.out.println("Invoking updateKeyword...");
        String _updateKeyword_freqId = "";
        String _updateKeyword_keyword = "";
        FreqWarningOperationResponse _updateKeyword__return = port.updateKeyword(_updateKeyword_freqId, _updateKeyword_keyword);
        System.out.println("updateKeyword.result=" + _updateKeyword__return);


        }
        {
        System.out.println("Invoking helloWorld...");
        String _helloWorld__return = port.helloWorld();
        System.out.println("helloWorld.result=" + _helloWorld__return);


        }
        {
        System.out.println("Invoking insertStat...");
        FreqWarningStatDTO _insertStat_dto = null;
        FreqWarningOperationResponse _insertStat__return = port.insertStat(_insertStat_dto);
        System.out.println("insertStat.result=" + _insertStat__return);


        }
        {
        System.out.println("Invoking insert...");
        FreqWarningDTO _insert_dto = null;
        FreqWarningOperationResponse _insert__return = port.insert(_insert_dto);
        System.out.println("insert.result=" + _insert__return);


        }
        {
        System.out.println("Invoking update...");
        FreqWarningDTO _update_dto = null;
        FreqWarningOperationResponse _update__return = port.update(_update_dto);
        System.out.println("update.result=" + _update__return);


        }

        System.exit(0);
    }

}
