package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-21T15:11:31.093+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "ImportFreqRangeManageService", 
                  wsdlLocation = "http://192.168.21.108:1234/bigdata/ImportFreqRangeManageService?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class ImportFreqRangeManageService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "ImportFreqRangeManageService");
    public final static QName NetTcpBindingIImportFreqRangeManageService = new QName("http://tempuri.org/", "NetTcpBinding_IImportFreqRangeManageService");
    public final static QName BasicHttpBindingIImportFreqRangeManageService = new QName("http://tempuri.org/", "BasicHttpBinding_IImportFreqRangeManageService");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.21.108:1234/bigdata/ImportFreqRangeManageService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ImportFreqRangeManageService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.21.108:1234/bigdata/ImportFreqRangeManageService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ImportFreqRangeManageService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ImportFreqRangeManageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImportFreqRangeManageService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ImportFreqRangeManageService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ImportFreqRangeManageService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ImportFreqRangeManageService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IImportFreqRangeManageService
     */
    @WebEndpoint(name = "NetTcpBinding_IImportFreqRangeManageService")
    public IImportFreqRangeManageService getNetTcpBindingIImportFreqRangeManageService() {
        return super.getPort(NetTcpBindingIImportFreqRangeManageService, IImportFreqRangeManageService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IImportFreqRangeManageService
     */
    @WebEndpoint(name = "NetTcpBinding_IImportFreqRangeManageService")
    public IImportFreqRangeManageService getNetTcpBindingIImportFreqRangeManageService(WebServiceFeature... features) {
        return super.getPort(NetTcpBindingIImportFreqRangeManageService, IImportFreqRangeManageService.class, features);
    }


    /**
     *
     * @return
     *     returns IImportFreqRangeManageService
     */
    @WebEndpoint(name = "BasicHttpBinding_IImportFreqRangeManageService")
    public IImportFreqRangeManageService getBasicHttpBindingIImportFreqRangeManageService() {
        return super.getPort(BasicHttpBindingIImportFreqRangeManageService, IImportFreqRangeManageService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IImportFreqRangeManageService
     */
    @WebEndpoint(name = "BasicHttpBinding_IImportFreqRangeManageService")
    public IImportFreqRangeManageService getBasicHttpBindingIImportFreqRangeManageService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIImportFreqRangeManageService, IImportFreqRangeManageService.class, features);
    }

}
