package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-07-14T14:25:18.002+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "RadioStationWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface RadioStationWebServiceSoap {

    @WebMethod(operationName = "RStatQuerySignalByFreqKey", action = "http://tempuri.org/RStatQuerySignalByFreqKey")
    @RequestWrapper(localName = "RStatQuerySignalByFreqKey", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RStatQuerySignalByFreqKey")
    @ResponseWrapper(localName = "RStatQuerySignalByFreqKeyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RStatQuerySignalByFreqKeyResponse")
    @WebResult(name = "RStatQuerySignalByFreqKeyResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.RStatQuerySignalByFreqKeyResponse2 rStatQuerySignalByFreqKey(
        @WebParam(name = "key", targetNamespace = "http://tempuri.org/")
        org.tempuri.RStatQuerySignalByFreqKeyRequest key
    );

    @WebMethod(operationName = "RStatInsertUpdateFreq", action = "http://tempuri.org/RStatInsertUpdateFreq")
    @RequestWrapper(localName = "RStatInsertUpdateFreq", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RStatInsertUpdateFreq")
    @ResponseWrapper(localName = "RStatInsertUpdateFreqResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RStatInsertUpdateFreqResponse")
    @WebResult(name = "RStatInsertUpdateFreqResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String rStatInsertUpdateFreq(
        @WebParam(name = "station", targetNamespace = "http://tempuri.org/")
        java.lang.String station,
        @WebParam(name = "freq", targetNamespace = "http://tempuri.org/")
        org.tempuri.RadioFreqDTO freq
    );

    @WebMethod(operationName = "RStatQueryAreas", action = "http://tempuri.org/RStatQueryAreas")
    @RequestWrapper(localName = "RStatQueryAreas", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RStatQueryAreas")
    @ResponseWrapper(localName = "RStatQueryAreasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RStatQueryAreasResponse")
    @WebResult(name = "RStatQueryAreasResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.ArrayOfString rStatQueryAreas();

    @WebMethod(operationName = "RStatInsertUpdateStation", action = "http://tempuri.org/RStatInsertUpdateStation")
    @RequestWrapper(localName = "RStatInsertUpdateStation", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RStatInsertUpdateStation")
    @ResponseWrapper(localName = "RStatInsertUpdateStationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RStatInsertUpdateStationResponse")
    @WebResult(name = "RStatInsertUpdateStationResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String rStatInsertUpdateStation(
        @WebParam(name = "station", targetNamespace = "http://tempuri.org/")
        org.tempuri.RadioStationDTO station
    );

    @WebMethod(operationName = "RStatDeleteFreq", action = "http://tempuri.org/RStatDeleteFreq")
    @RequestWrapper(localName = "RStatDeleteFreq", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RStatDeleteFreq")
    @ResponseWrapper(localName = "RStatDeleteFreqResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RStatDeleteFreqResponse")
    public void rStatDeleteFreq(
        @WebParam(name = "freqs", targetNamespace = "http://tempuri.org/")
        org.tempuri.ArrayOfString freqs
    );

    @WebMethod(operationName = "RStatQueryStatName", action = "http://tempuri.org/RStatQueryStatName")
    @RequestWrapper(localName = "RStatQueryStatName", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RStatQueryStatName")
    @ResponseWrapper(localName = "RStatQueryStatNameResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RStatQueryStatNameResponse")
    @WebResult(name = "RStatQueryStatNameResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.ArrayOfString rStatQueryStatName(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.tempuri.RStatQueryStatNameRequest request
    );

    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorldResponse")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String helloWorld();

    @WebMethod(operationName = "RStatQuerySignals", action = "http://tempuri.org/RStatQuerySignals")
    @RequestWrapper(localName = "RStatQuerySignals", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RStatQuerySignals")
    @ResponseWrapper(localName = "RStatQuerySignalsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RStatQuerySignalsResponse")
    @WebResult(name = "RStatQuerySignalsResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.RStatQuerySignalsResponse2 rStatQuerySignals(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.tempuri.RStatQuerySignalsRequest request
    );

    @WebMethod(operationName = "RStatDeleteStation", action = "http://tempuri.org/RStatDeleteStation")
    @RequestWrapper(localName = "RStatDeleteStation", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RStatDeleteStation")
    @ResponseWrapper(localName = "RStatDeleteStationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RStatDeleteStationResponse")
    public void rStatDeleteStation(
        @WebParam(name = "stations", targetNamespace = "http://tempuri.org/")
        org.tempuri.ArrayOfString stations
    );
}
