package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-07-14T14:25:18.018+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "RadioStationWebService", 
                  wsdlLocation = "http://192.168.21.2:8000/RadioStationWebService.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class RadioStationWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "RadioStationWebService");
    public final static QName RadioStationWebServiceSoap = new QName("http://tempuri.org/", "RadioStationWebServiceSoap");
    public final static QName RadioStationWebServiceSoap12 = new QName("http://tempuri.org/", "RadioStationWebServiceSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.21.2:8000/RadioStationWebService.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RadioStationWebService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.21.2:8000/RadioStationWebService.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RadioStationWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RadioStationWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RadioStationWebService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public RadioStationWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RadioStationWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RadioStationWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns RadioStationWebServiceSoap
     */
    @WebEndpoint(name = "RadioStationWebServiceSoap")
    public RadioStationWebServiceSoap getRadioStationWebServiceSoap() {
        return super.getPort(RadioStationWebServiceSoap, RadioStationWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RadioStationWebServiceSoap
     */
    @WebEndpoint(name = "RadioStationWebServiceSoap")
    public RadioStationWebServiceSoap getRadioStationWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(RadioStationWebServiceSoap, RadioStationWebServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns RadioStationWebServiceSoap
     */
    @WebEndpoint(name = "RadioStationWebServiceSoap12")
    public RadioStationWebServiceSoap getRadioStationWebServiceSoap12() {
        return super.getPort(RadioStationWebServiceSoap12, RadioStationWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RadioStationWebServiceSoap
     */
    @WebEndpoint(name = "RadioStationWebServiceSoap12")
    public RadioStationWebServiceSoap getRadioStationWebServiceSoap12(WebServiceFeature... features) {
        return super.getPort(RadioStationWebServiceSoap12, RadioStationWebServiceSoap.class, features);
    }

}
