package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-07-18T15:04:53.194+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "RadioSignalWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface RadioSignalWebServiceSoap {

    @WebMethod(operationName = "InsertAbnormalHistory", action = "http://tempuri.org/InsertAbnormalHistory")
    @RequestWrapper(localName = "InsertAbnormalHistory", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertAbnormalHistory")
    @ResponseWrapper(localName = "InsertAbnormalHistoryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertAbnormalHistoryResponse")
    @WebResult(name = "InsertAbnormalHistoryResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.RadioSignalOperationReponse insertAbnormalHistory(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.tempuri.RadioSignalAbnormalHistoryDTO request
    );

    @WebMethod(operationName = "QueryRadioSignal", action = "http://tempuri.org/QueryRadioSignal")
    @RequestWrapper(localName = "QueryRadioSignal", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryRadioSignal")
    @ResponseWrapper(localName = "QueryRadioSignalResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryRadioSignalResponse")
    @WebResult(name = "QueryRadioSignalResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.RadioSignalQueryResponse queryRadioSignal(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.tempuri.RadioSignalQueryRequest request
    );

    @WebMethod(operationName = "UpdateAbnormalHistory", action = "http://tempuri.org/UpdateAbnormalHistory")
    @RequestWrapper(localName = "UpdateAbnormalHistory", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateAbnormalHistory")
    @ResponseWrapper(localName = "UpdateAbnormalHistoryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateAbnormalHistoryResponse")
    @WebResult(name = "UpdateAbnormalHistoryResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.RadioSignalOperationReponse updateAbnormalHistory(
        @WebParam(name = "info", targetNamespace = "http://tempuri.org/")
        org.tempuri.RadioSignalAbnormalHistoryDTO info
    );

    @WebMethod(operationName = "InsertRadioSignal", action = "http://tempuri.org/InsertRadioSignal")
    @RequestWrapper(localName = "InsertRadioSignal", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertRadioSignal")
    @ResponseWrapper(localName = "InsertRadioSignalResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertRadioSignalResponse")
    @WebResult(name = "InsertRadioSignalResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.RadioSignalOperationReponse insertRadioSignal(
        @WebParam(name = "Info", targetNamespace = "http://tempuri.org/")
        org.tempuri.RadioSignalDTO info
    );

    @WebMethod(operationName = "RemoveAbnormalHistory", action = "http://tempuri.org/RemoveAbnormalHistory")
    @RequestWrapper(localName = "RemoveAbnormalHistory", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveAbnormalHistory")
    @ResponseWrapper(localName = "RemoveAbnormalHistoryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveAbnormalHistoryResponse")
    @WebResult(name = "RemoveAbnormalHistoryResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.RadioSignalOperationReponse removeAbnormalHistory(
        @WebParam(name = "ID", targetNamespace = "http://tempuri.org/")
        java.lang.String id
    );

    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorldResponse")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String helloWorld();

    @WebMethod(operationName = "QueryAbnormalHistory", action = "http://tempuri.org/QueryAbnormalHistory")
    @RequestWrapper(localName = "QueryAbnormalHistory", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryAbnormalHistory")
    @ResponseWrapper(localName = "QueryAbnormalHistoryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryAbnormalHistoryResponse")
    @WebResult(name = "QueryAbnormalHistoryResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.AbnormalHistoryQueryResponse queryAbnormalHistory(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.tempuri.AbnormalHistoryRequest request
    );

    @WebMethod(operationName = "UpdateRadioSignal", action = "http://tempuri.org/UpdateRadioSignal")
    @RequestWrapper(localName = "UpdateRadioSignal", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateRadioSignal")
    @ResponseWrapper(localName = "UpdateRadioSignalResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateRadioSignalResponse")
    @WebResult(name = "UpdateRadioSignalResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.RadioSignalOperationReponse updateRadioSignal(
        @WebParam(name = "info", targetNamespace = "http://tempuri.org/")
        org.tempuri.RadioSignalDTO info
    );

    @WebMethod(operationName = "RemoveRadioSignal", action = "http://tempuri.org/RemoveRadioSignal")
    @RequestWrapper(localName = "RemoveRadioSignal", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveRadioSignal")
    @ResponseWrapper(localName = "RemoveRadioSignalResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveRadioSignalResponse")
    @WebResult(name = "RemoveRadioSignalResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.RadioSignalOperationReponse removeRadioSignal(
        @WebParam(name = "freqIDs", targetNamespace = "http://tempuri.org/")
        org.tempuri.ArrayOfString freqIDs
    );

    @WebMethod(operationName = "QueryRadioSignalClassified", action = "http://tempuri.org/QueryRadioSignalClassified")
    @RequestWrapper(localName = "QueryRadioSignalClassified", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryRadioSignalClassified")
    @ResponseWrapper(localName = "QueryRadioSignalClassifiedResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryRadioSignalClassifiedResponse")
    @WebResult(name = "QueryRadioSignalClassifiedResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.RadioSignalClassifiedQueryResponse queryRadioSignalClassified(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.tempuri.RadioSignalClassifiedQueryRequest request
    );
}
