
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.tempuri;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-07-29T14:14:21.023+08:00
 * Generated source version: 3.1.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "RadioSignalWebService",
                      portName = "RadioSignalWebServiceSoap",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "http://192.168.21.2:8000/RadioSignalWebService.asmx?wsdl",
                      endpointInterface = "org.tempuri.RadioSignalWebServiceSoap")
                      
public class RadioSignalWebServiceSoapImpl implements RadioSignalWebServiceSoap {

    private static final Logger LOG = Logger.getLogger(RadioSignalWebServiceSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see org.tempuri.RadioSignalWebServiceSoap#insertAbnormalHistory(org.tempuri.RadioSignalAbnormalHistoryDTO request)*
     */
    public org.tempuri.RadioSignalOperationReponse insertAbnormalHistory(org.tempuri.RadioSignalAbnormalHistoryDTO request) { 
        LOG.info("Executing operation insertAbnormalHistory");
        System.out.println(request);
        try {
            org.tempuri.RadioSignalOperationReponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.RadioSignalWebServiceSoap#queryRadioSignal(org.tempuri.RadioSignalQueryRequest request)*
     */
    public org.tempuri.RadioSignalQueryResponse queryRadioSignal(org.tempuri.RadioSignalQueryRequest request) { 
        LOG.info("Executing operation queryRadioSignal");
        System.out.println(request);
        try {
            org.tempuri.RadioSignalQueryResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.RadioSignalWebServiceSoap#updateAbnormalHistory(org.tempuri.RadioSignalAbnormalHistoryDTO info)*
     */
    public org.tempuri.RadioSignalOperationReponse updateAbnormalHistory(org.tempuri.RadioSignalAbnormalHistoryDTO info) { 
        LOG.info("Executing operation updateAbnormalHistory");
        System.out.println(info);
        try {
            org.tempuri.RadioSignalOperationReponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.RadioSignalWebServiceSoap#insertRadioSignal(org.tempuri.RadioSignalDTO info)*
     */
    public org.tempuri.RadioSignalOperationReponse insertRadioSignal(org.tempuri.RadioSignalDTO info) { 
        LOG.info("Executing operation insertRadioSignal");
        System.out.println(info);
        try {
            org.tempuri.RadioSignalOperationReponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.RadioSignalWebServiceSoap#updateRadioSignalForRequest(org.tempuri.RadioSignalUpdateRequest request)*
     */
    public org.tempuri.RadioSignalOperationReponse updateRadioSignalForRequest(org.tempuri.RadioSignalUpdateRequest request) { 
        LOG.info("Executing operation updateRadioSignalForRequest");
        System.out.println(request);
        try {
            org.tempuri.RadioSignalOperationReponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.RadioSignalWebServiceSoap#removeAbnormalHistory(java.lang.String id)*
     */
    public org.tempuri.RadioSignalOperationReponse removeAbnormalHistory(java.lang.String id) { 
        LOG.info("Executing operation removeAbnormalHistory");
        System.out.println(id);
        try {
            org.tempuri.RadioSignalOperationReponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.RadioSignalWebServiceSoap#helloWorld()*
     */
    public java.lang.String helloWorld() { 
        LOG.info("Executing operation helloWorld");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.RadioSignalWebServiceSoap#queryAbnormalHistory(org.tempuri.AbnormalHistoryRequest request)*
     */
    public org.tempuri.AbnormalHistoryQueryResponse queryAbnormalHistory(org.tempuri.AbnormalHistoryRequest request) { 
        LOG.info("Executing operation queryAbnormalHistory");
        System.out.println(request);
        try {
            org.tempuri.AbnormalHistoryQueryResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.RadioSignalWebServiceSoap#updateRadioSignal(org.tempuri.RadioSignalDTO info)*
     */
    public org.tempuri.RadioSignalOperationReponse updateRadioSignal(org.tempuri.RadioSignalDTO info) { 
        LOG.info("Executing operation updateRadioSignal");
        System.out.println(info);
        try {
            org.tempuri.RadioSignalOperationReponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.RadioSignalWebServiceSoap#removeRadioSignal(org.tempuri.ArrayOfString freqIDs)*
     */
    public org.tempuri.RadioSignalOperationReponse removeRadioSignal(org.tempuri.ArrayOfString freqIDs) { 
        LOG.info("Executing operation removeRadioSignal");
        System.out.println(freqIDs);
        try {
            org.tempuri.RadioSignalOperationReponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.RadioSignalWebServiceSoap#queryRadioSignalClassified(org.tempuri.RadioSignalClassifiedQueryRequest request)*
     */
    public org.tempuri.RadioSignalClassifiedQueryResponse queryRadioSignalClassified(org.tempuri.RadioSignalClassifiedQueryRequest request) { 
        LOG.info("Executing operation queryRadioSignalClassified");
        System.out.println(request);
        try {
            org.tempuri.RadioSignalClassifiedQueryResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
