package com.sefon.ws.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-08-03T10:24:19.347+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://impl.service.ws.sefon.com", name = "QueryToolsServicePortType")
@XmlSeeAlso({ObjectFactory.class, com.sefon.ws.model.freq.xsd.ObjectFactory.class})
public interface QueryToolsServicePortType {

    @WebMethod(action = "urn:querySelfFreqInfoByID")
    @Action(input = "urn:querySelfFreqInfoByID", output = "urn:querySelfFreqInfoByIDResponse")
    @RequestWrapper(localName = "querySelfFreqInfoByID", targetNamespace = "http://impl.service.ws.sefon.com", className = "com.sefon.ws.service.impl.QuerySelfFreqInfoByID")
    @ResponseWrapper(localName = "querySelfFreqInfoByIDResponse", targetNamespace = "http://impl.service.ws.sefon.com", className = "com.sefon.ws.service.impl.QuerySelfFreqInfoByIDResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.service.ws.sefon.com")
    public java.util.List<com.sefon.ws.model.freq.xsd.FreqSelfInfo> querySelfFreqInfoByID(
        @WebParam(name = "id", targetNamespace = "http://impl.service.ws.sefon.com")
        java.lang.String id
    );
}
