package com.sefon.ws.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-12-05T13:51:55.887+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://impl.service.ws.sefon.com", name = "StationServicePortType")
@XmlSeeAlso({ObjectFactory.class, com.sefon.ws.model.xsd.ObjectFactory.class})
public interface StationServicePortType {

    @WebMethod(operationName = "QueryStationWithPagination", action = "urn:QueryStationWithPagination")
    @Action(input = "urn:QueryStationWithPagination", output = "urn:QueryStationWithPaginationResponse")
    @RequestWrapper(localName = "QueryStationWithPagination", targetNamespace = "http://impl.service.ws.sefon.com", className = "com.sefon.ws.service.impl.QueryStationWithPagination")
    @ResponseWrapper(localName = "QueryStationWithPaginationResponse", targetNamespace = "http://impl.service.ws.sefon.com", className = "com.sefon.ws.service.impl.QueryStationWithPaginationResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.service.ws.sefon.com")
    public com.sefon.ws.model.xsd.StationInfoPagedResult queryStationWithPagination(
        @WebParam(name = "spec", targetNamespace = "http://impl.service.ws.sefon.com")
        com.sefon.ws.model.xsd.StationQuerySpecInfo spec,
        @WebParam(name = "pageNum", targetNamespace = "http://impl.service.ws.sefon.com")
        java.lang.Integer pageNum,
        @WebParam(name = "pageSize", targetNamespace = "http://impl.service.ws.sefon.com")
        java.lang.Integer pageSize
    );

    @WebMethod(operationName = "QueryStation", action = "urn:QueryStation")
    @Action(input = "urn:QueryStation", output = "urn:QueryStationResponse")
    @RequestWrapper(localName = "QueryStation", targetNamespace = "http://impl.service.ws.sefon.com", className = "com.sefon.ws.service.impl.QueryStation")
    @ResponseWrapper(localName = "QueryStationResponse", targetNamespace = "http://impl.service.ws.sefon.com", className = "com.sefon.ws.service.impl.QueryStationResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.service.ws.sefon.com")
    public java.util.List<com.sefon.ws.model.xsd.StationInfo> queryStation(
        @WebParam(name = "spec", targetNamespace = "http://impl.service.ws.sefon.com")
        com.sefon.ws.model.xsd.StationQuerySpecInfo spec,
        @WebParam(name = "removeSame", targetNamespace = "http://impl.service.ws.sefon.com")
        java.lang.Boolean removeSame
    );

    @WebMethod(operationName = "GetStationById", action = "urn:GetStationById")
    @Action(input = "urn:GetStationById", output = "urn:GetStationByIdResponse")
    @RequestWrapper(localName = "GetStationById", targetNamespace = "http://impl.service.ws.sefon.com", className = "com.sefon.ws.service.impl.GetStationById")
    @ResponseWrapper(localName = "GetStationByIdResponse", targetNamespace = "http://impl.service.ws.sefon.com", className = "com.sefon.ws.service.impl.GetStationByIdResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.service.ws.sefon.com")
    public com.sefon.ws.model.xsd.StationInfo getStationById(
        @WebParam(name = "id", targetNamespace = "http://impl.service.ws.sefon.com")
        java.lang.String id
    );
}
